[0m[[0m[0mdebug[0m] [0m[0mStarting process: node[0m
[0m[[0m[31merror[0m] [0m[0mjava.io.IOException: Cannot run program "node": error=2, No such file or directory[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.startExternalJSEnv(ExternalJSEnv.scala:222)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.start(ExternalJSEnv.scala:210)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.startManagedRunner(TestAdapter.scala:196)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:128)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.getRunnerForThread(TestAdapter.scala:128)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.loadFrameworks(TestAdapter.scala:53)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestFrameworkSettings$1(ScalaJSPluginInternal.scala:1037)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.Function1.$anonfun$compose$1(Function1.scala:49)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.std.Transform$$anon$4.work(Transform.scala:67)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Execute.work(Execute.scala:290)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:834)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.io.IOException: error=2, No such file or directory[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.startExternalJSEnv(ExternalJSEnv.scala:222)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.start(ExternalJSEnv.scala:210)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.startManagedRunner(TestAdapter.scala:196)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:128)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.getRunnerForThread(TestAdapter.scala:128)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.testadapter.TestAdapter.loadFrameworks(TestAdapter.scala:53)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestFrameworkSettings$1(ScalaJSPluginInternal.scala:1037)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.Function1.$anonfun$compose$1(Function1.scala:49)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.std.Transform$$anon$4.work(Transform.scala:67)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Execute.work(Execute.scala:290)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:834)[0m
[0m[[0m[31merror[0m] [0m[0m(capstoneUI / Test / [31mloadedTestFrameworks[0m) java.io.IOException: Cannot run program "node": error=2, No such file or directory[0m
